### ISSUE TITLE
Ensure that Stripe webhooks work

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#100]
- [X] Locally for now
- [x] Server

```
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]Internal Server Error: /stripe/webhook/
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]Traceback (most recent call last):
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/models/base.py", line 583, in _create_from_stripe_object
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    instance = cls.stripe_objects.get(id=id_)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return getattr(self.get_queryset(), name)(*args, **kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 496, in get
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    raise self.model.DoesNotExist(
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]djstripe.models.core.Event.DoesNotExist: Event matching query does not exist.
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]During handling of the above exception, another exception occurred:
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]Traceback (most recent call last):
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return self.cursor.execute(sql, params)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]psycopg2.errors.StringDataRightTruncation: value too long for type character varying(15)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]The above exception was the direct cause of the following exception:
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]Traceback (most recent call last):
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    response = get_response(request)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return self.dispatch(request, *args, **kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return bound_method(*args, **kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return view_func(*args, **kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return handler(request, *args, **kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/views.py", line 36, in post
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    trigger = WebhookEventTrigger.from_request(request)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/models/webhooks.py", line 217, in from_request
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    raise e
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/models/webhooks.py", line 203, in from_request
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    obj.process(save=False)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/models/webhooks.py", line 294, in process
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    self.event = Event.process(self.json_body)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/models/core.py", line 1524, in process
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    ret = cls._create_from_stripe_object(data)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/djstripe/models/base.py", line 596, in _create_from_stripe_object
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    instance.save()
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    self.save_base(
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    updated = self._save_table(
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    results = self._do_insert(
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return manager._insert(
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return getattr(self.get_queryset(), name)(*args, **kwargs)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return query.get_compiler(using=using).execute_sql(returning_fields)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    cursor.execute(sql, params)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return self._execute_with_wrappers(
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return executor(sql, params, many, context)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return self.cursor.execute(sql, params)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    raise dj_exc_value.with_traceback(traceback) from exc_value
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]  File "/app/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]    return self.cursor.execute(sql, params)
2022-05-02T01:44:00Z app[ce6f9f52] lhr [info]django.db.utils.DataError: value too long for type character varying(15)
```

**Comment by janbaykara** [comment]
Added a fix for this upstream in the djstripe library: https://github.com/dj-stripe/dj-stripe/pull/1677
